### ISSUE TITLE
i cant write files

### ISSUE THREAD

**Issue by BlackDemonHat** [dbisu/pico-ducky#86]
![image](https://user-images.githubusercontent.com/105757180/180750694-6ea740fe-4f7b-4cbc-8227-93c64b471592.png)

says that only system read files only

**Comment by dbisu** [comment]
By default, the internal storage is mounted read-only by CircuitPython so that the host computer can write to it.
You can remount the storage as read-write.  This needs to be done with caution, as there is potential for the filesystem to become corrupted if state isn't maintained.  You can learn more about it here:
https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage
and
https://docs.circuitpython.org/en/latest/shared-bindings/storage/index.html
